# Generated by Django 5.0.6 on 2024-08-12 07:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
        ('users', '0004_remove_jobseeker_resume_url_jobseeker_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('application_screening', 'Application Screening'), ('phone_interview', 'Phone Interview'), ('technical_assessment', 'Technical Assessment'), ('first_round_interview', 'First Round Interview'), ('second_round_interview', 'Second Round Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('job_offer', 'Job Offer'), ('hired', 'Hired')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('provided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='users.employer')),
                ('interview_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Interview.interviewschedule')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='users.jobseeker')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.interviewstage')),
            ],
            options={
                'unique_together': {('employer', 'job_seeker', 'interview_schedule', 'stage')},
            },
        ),
    ]
