# Generated by Django 5.0.6 on 2024-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_interviewstage_interviewfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='stage',
            field=models.CharField(choices=[('application_screening', 'Application Screening'), ('phone_interview', 'Phone Interview'), ('technical_assessment', 'Technical Assessment'), ('first_round_interview', 'First Round Interview'), ('second_round_interview', 'Second Round Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('job_offer', 'Job Offer'), ('hired', 'Hired')], max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='InterviewStage',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='interviewfeedback',
            name='job_seeker',
        ),
    ]
