# Generated by Django 5.0.6 on 2024-08-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0003_alter_interviewfeedback_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Interview.interviewschedule'),
        ),
    ]
