# Generated by Django 5.0.6 on 2024-08-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0004_alter_interviewfeedback_interview_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
