# Generated by Django 5.0.6 on 2024-07-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_company_gst_document_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylocation',
            name='location',
        ),
    ]
