# Generated by Django 5.0.6 on 2024-07-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_companylocation_location'),
        ('users', '0012_remove_employer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='users.employer'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='location',
            field=models.CharField(default='default_location', max_length=100),
        ),
    ]
