# Generated by Django 5.0.6 on 2024-08-01 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
