# Generated by Django 5.0.6 on 2024-08-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
    ]
