# Generated by Django 5.0.6 on 2024-07-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.employer'),
        ),
        migrations.AddField(
            model_name='jobcategoryrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobcategoryrelation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcategoryrelation_set', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcategoryrelation',
            unique_together={('job', 'category')},
        ),
    ]
