# Generated by Django 5.0.6 on 2024-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
