# Generated by Django 5.0.6 on 2024-08-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
        ('users', '0004_remove_jobseeker_resume_url_jobseeker_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.jobseeker'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.jobseeker'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='users.jobseeker'),
        ),
    ]
