# Generated by Django 5.0.6 on 2024-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employer_company_details_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
