# Generated by Django 5.0.6 on 2024-08-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_jobseeker_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='jobseeker_resumes/'),
        ),
    ]
