# Generated by Django 4.2.7 on 2024-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_employer_company_name_employer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], default='admin', max_length=50),
        ),
    ]
