# Generated by Django 5.0.6 on 2024-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_jobseeker_resume_url_jobseeker_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='visible_applications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
