# Generated by Django 5.0.6 on 2024-07-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_employer_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
