# Generated by Django 5.0.6 on 2024-07-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_employer_is_approved_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
