# Generated by Django 5.0.6 on 2024-07-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_recruiter_company_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company',
        ),
    ]
